name: Build PyInstaller Executable

on:
    workflow_dispatch:
    pull_request:
jobs:
    buildwindows:
        runs-on: windows-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: Install dependencies
          run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install -r quality.txt

        - name: Build executable
          run: |
                pyinstaller --noconfirm .\pyx2cscope_win.spec

        - name: Create startWebInterface.bat
          shell: cmd
          run: |
                echo pyX2Cscope.exe -w > dist\pyx2cscope\startWebInterface.bat

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
                name: pyX2Cscope-windows
                path: dist/pyX2Cscope


    buildlinux:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
                python-version: '3.10'

        - name: Install dependencies
          run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install -r quality.txt

        - name: Build executable
          run: |
                pyinstaller --noconfirm ./pyx2cscope_linux.spec

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
                name: pyX2Cscope-linux
                path: dist/pyX2Cscope_linux
